export const HOME = 'Home'
export const PROFILE = 'Profile'
export const CHATS = 'Chats'
export const CHAT_ROOM = 'ChatRoom'
export const FAVORITES = 'Favorites'
export const SPLASH = 'SPLASH'
export const SIGNIN = 'SignIn'
export const SIGNUP = 'SignUp'
