export const HOME = 'Home'
export const PROFILE = 'Profile'
export const MESSAGES = 'Messages'
export const FAVORITES = 'Favorites'
export const SPLASH = 'SPLASH'
export const SIGNIN = 'SignIn'
export const SIGNUP = 'SignUp'
